import { access, readFile } from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { acquireLock, changedPaths, codexCommand, defaults, documentationPolicyEligible, issueAllowedPaths, parseConfig, requiredTerms, runOnce, runWatch, sanitize, writeAudit } from './core.mjs';

const root = process.cwd(); const command = process.argv[2]; const config = parseConfig(process.argv.slice(3)); const requiredFiles = ['AGENTS.md', 'README.md', 'docs/AGENT_BRIDGE.md', 'docs/BRIDGE_RUNBOOK.md'];
function execute(commandName, args, { cwd = root, input } = {}) { return new Promise((resolve, reject) => { const child = spawn(commandName, args, { cwd, shell: false, stdio: ['pipe', 'pipe', 'pipe'] }); let stdout = ''; let stderr = ''; child.stdout.on('data', (chunk) => { stdout += chunk; }); child.stderr.on('data', (chunk) => { stderr += chunk; }); child.on('error', reject); child.on('close', (code) => code === 0 ? resolve(stdout) : reject(new Error(`${commandName} failed (${code}): ${sanitize(stderr)}`))); child.stdin.end(input); }); }
function executeChild(commandName, args, { cwd, onProgress }) { return new Promise((resolve, reject) => { const child = spawn(commandName, args, { cwd, shell: false, stdio: ['pipe', 'pipe', 'pipe'] }); let stdout = ''; let stderr = ''; const heartbeat = setInterval(() => onProgress?.({ phase: 'run-child', event: 'heartbeat' }), 30_000); child.stdout.on('data', (chunk) => { stdout += chunk; onProgress?.({ phase: 'run-child', event: 'output' }); }); child.stderr.on('data', (chunk) => { stderr += chunk; onProgress?.({ phase: 'run-child', event: 'diagnostic-output' }); }); child.on('error', (error) => { clearInterval(heartbeat); reject(error); }); child.on('close', (exitCode) => { clearInterval(heartbeat); onProgress?.({ phase: 'run-child', event: 'exit', exitCode }); resolve({ exitCode, summary: stdout.slice(-1000), diagnostics: stderr.slice(-1000) }); }); child.stdin.end(); }); }
const gh = (args) => execute('gh', args); const git = (args, cwd = root) => execute('git', ['-C', cwd, ...args]);
async function codexInvocation() { if (process.platform !== 'win32') return { command: codexCommand(), args: [] }; const shim = (await execute('where.exe', ['codex.cmd'])).split(/\r?\n/).find(Boolean); const entry = path.join(path.dirname(shim), 'node_modules', '@openai', 'codex', 'bin', 'codex.js'); await access(entry); return { command: process.execPath, args: [entry] }; }
async function checkGit(name, cwd, args) { try { await git(args, cwd); return { name, pass: true }; } catch { return { name, pass: false }; } }
const adapter = {
  listReadyIssues: async () => JSON.parse(await gh(['issue', 'list', '--state', 'open', '--label', 'agent:ready', '--limit', '100', '--json', 'number,title,body,labels,createdAt'])),
  getIssue: async (number) => JSON.parse(await gh(['issue', 'view', String(number), '--json', 'number,title,body,labels,createdAt,assignees'])),
  claimIssue: async (number) => gh(['issue', 'edit', String(number), '--remove-label', 'agent:ready', '--add-label', 'agent:running', '--add-assignee', '@me']),
  blockIssue: async (number, message) => { await gh(['issue', 'edit', String(number), '--remove-label', 'agent:running', '--add-label', 'agent:blocked']); await gh(['issue', 'comment', String(number), '--body', message]); },
  handoff: async (number, id, branch, pullRequest) => { await gh(['issue', 'edit', String(number), '--remove-label', 'agent:running', '--add-label', 'agent:review']); await gh(['issue', 'comment', String(number), '--body', `Bridge handoff: run ${id}; branch ${branch}; PR #${pullRequest}; audit report stored locally.`]); },
  createWorktree: async (branch, worktree) => git(['worktree', 'add', '-b', branch, worktree, 'origin/main']),
  worktreePath: (workspace, branch) => path.join(workspace, '.agent-bridge', 'worktrees', branch.replaceAll('/', '-')),
  runCodex: async (prompt, cwd, { onProgress } = {}) => { const invocation = await codexInvocation(); return executeChild(invocation.command, [...invocation.args, 'exec', '--ephemeral', prompt], { cwd, onProgress }); },
  acquireLock: (workspace) => acquireLock(workspace),
  writeAudit: (workspace, id, report) => writeAudit(workspace, id, report),
  inspectWorktree: async (worktree) => { const status = await git(['status', '--short', '--untracked-files=all'], worktree); const paths = changedPaths(status); return { changedPaths: paths, stagedPaths: paths, untrackedPaths: paths }; },
  validateChanges: async (worktree, paths) => { const permitted = validatePaths(paths); if (!permitted.valid) throw new Error(`out-of-scope changed paths: ${permitted.invalid.join(', ')}`); for (const file of paths) { const content = await readFile(path.join(worktree, file), 'utf8'); if (/^(<<<<<<<|=======|>>>>>>>)/m.test(content)) throw new Error('conflict markers found'); if (/(gh[pousr]_|github_pat_)/.test(content)) throw new Error('possible secret found'); } },
  runChecks: async (worktree, issue, paths) => { const checks = [await checkGit('git diff --check', worktree, ['diff', '--check'])]; const terms = requiredTerms(issue); const glossary = paths.find((file) => file.endsWith('BRIDGE_GLOSSARY.md')); if (glossary) { const content = await readFile(path.join(worktree, glossary), 'utf8'); for (const term of terms) checks.push({ name: `required term: ${term}`, pass: content.includes(term) }); } return checks; },
  commit: async (worktree, branch, paths, message) => { await git(['add', '--', ...paths], worktree); await git(['diff', '--cached', '--check'], worktree); await git(['commit', '-m', message], worktree); return (await git(['rev-parse', 'HEAD'], worktree)).trim(); },
  push: async (worktree, branch) => { await git(['push', '-u', 'origin', branch], worktree); },
  createPR: async (issue, branch, body) => { const output = await gh(['pr', 'create', '--base', 'main', '--head', branch, '--title', issue.title, '--body', body]); return { number: Number(output.match(/\/pull\/(\d+)/)?.[1]) }; },
  getHandoffStatus: async (branch) => { const prs = JSON.parse(await gh(['pr', 'list', '--head', branch, '--state', 'open', '--json', 'number'])); if (prs.length !== 1) return { ready: false, reason: `handoff requires exactly one open pull request for ${branch}; found ${prs.length}` }; return { ready: true, number: prs[0].number }; },
  waitForChecks: async (number) => { for (let attempt = 0; attempt < 30; attempt += 1) { const pr = JSON.parse(await gh(['pr', 'view', String(number), '--json', 'statusCheckRollup'])); const checks = pr.statusCheckRollup || []; if (checks.length && checks.every((check) => check.conclusion === 'SUCCESS')) return { pass: true, checks: checks.map((check) => ({ name: check.name, pass: true })) }; if (checks.some((check) => check.conclusion === 'FAILURE' || check.conclusion === 'CANCELLED')) return { pass: false, checks: checks.map((check) => ({ name: check.name, pass: check.conclusion === 'SUCCESS' })) }; await new Promise((resolve) => setTimeout(resolve, 2_000)); } return { pass: false, checks: [] }; },
  getMergeStatus: async (branch, issue) => { const prs = JSON.parse(await gh(['pr', 'list', '--head', branch, '--state', 'open', '--json', 'number,isDraft,mergeStateStatus,statusCheckRollup,files,body,headRefOid'])); if (prs.length !== 1) return { policyEligible: false, requiredChecksPass: false, mergeable: false, clean: false, files: [] }; const pr = prs[0]; const checks = pr.statusCheckRollup || []; const contract = /## Issue[\s\S]*## Summary[\s\S]*## Changes[\s\S]*## Checks[\s\S]*## Migrations and configuration[\s\S]*## Screenshots[\s\S]*## Risks and limitations[\s\S]*## Rollback[\s\S]*## Handoff/i.test(pr.body || '') && new RegExp(`Closes #${issue.number}\\b`, 'i').test(pr.body || ''); const requiredChecksPass = contract && checks.length > 0 && checks.every((check) => check.status === 'COMPLETED' && check.conclusion === 'SUCCESS'); return { number: pr.number, files: pr.files, policyEligible: documentationPolicyEligible({ files: pr.files, issueAllowedPaths: issueAllowedPaths(issue), labels: issue.labels || [] }), requiredChecksPass, mergeable: !pr.isDraft, clean: pr.mergeStateStatus === 'CLEAN', headSha: pr.headRefOid, checks }; },
  mergePR: (number) => gh(['pr', 'merge', String(number), '--merge']),
  verifyClosure: async (number) => (JSON.parse(await gh(['issue', 'view', String(number), '--json', 'state'])).state === 'CLOSED'),
  cleanup: async (workspace, worktree, branch) => { const state = await git(['status', '--short'], worktree); if (state.trim()) throw new Error('refusing to clean dirty worktree'); await git(['pull', '--ff-only', 'origin', 'main'], workspace); await git(['worktree', 'remove', worktree], workspace); await git(['worktree', 'prune'], workspace); try { await git(['branch', '-d', branch], workspace); } catch (error) { if (!/not found|not exist|does not exist/i.test(String(error.message))) throw error; } return { removed: true, pruned: true }; }
};
function validatePaths(paths) { return { valid: paths.every((file) => !file.startsWith('/') && !file.includes('..')), invalid: paths.filter((file) => file.startsWith('/') || file.includes('..')) }; }
async function doctor() { const checks = []; const codex = await codexInvocation().catch((error) => ({ error })); for (const [name, executable, args] of [['git', 'git', ['--version']], ['gh-auth', 'gh', ['auth', 'status']], ['codex', codex.command, [...(codex.args || []), 'exec', '--help']]]) { try { if (codex.error && name === 'codex') throw codex.error; await execute(executable, args); checks.push({ name, pass: true }); } catch (error) { checks.push({ name, pass: false, detail: sanitize(error.message) }); } } for (const file of requiredFiles) { try { await access(path.join(root, file)); checks.push({ name: file, pass: true }); } catch { checks.push({ name: file, pass: false }); } } const status = await git(['status', '--short']); const branch = (await git(['branch', '--show-current'])).trim(); checks.push({ name: 'clean-main', pass: branch === 'main' && status.trim() === '' }); try { const labels = JSON.parse(await gh(['label', 'list', '--limit', '100', '--json', 'name'])).map((label) => label.name); checks.push({ name: 'bridge-labels', pass: ['agent:ready', 'agent:running', 'agent:review', 'agent:blocked'].every((label) => labels.includes(label)) }); } catch (error) { checks.push({ name: 'bridge-labels', pass: false, detail: sanitize(error.message) }); } console.log(JSON.stringify({ command: 'doctor', defaults, checks }, null, 2)); if (checks.some((check) => !check.pass)) process.exitCode = 1; }
const reportProgress = (event) => console.log(JSON.stringify({ event: 'bridge-progress', ...event }));
if (command === 'doctor') await doctor(); else if (command === 'once') console.log(JSON.stringify(await runOnce({ adapter, root, config, progress: reportProgress }), null, 2)); else if (command === 'watch') console.log(JSON.stringify(await runWatch({ adapter, root, config }), null, 2)); else { console.error('Usage: bridge <doctor|once|watch> [--dry-run] [--auto-merge]'); process.exitCode = 2; }
