import { access } from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { acquireLock, codexCommand, defaults, parseConfig, runOnce, runWatch, sanitize, writeAudit } from './core.mjs';

const root = process.cwd(); const command = process.argv[2]; const config = parseConfig(process.argv.slice(3)); const requiredFiles = ['AGENTS.md', 'README.md', 'docs/AGENT_BRIDGE.md', 'docs/BRIDGE_RUNBOOK.md'];
function execute(commandName, args, { cwd = root, input } = {}) { return new Promise((resolve, reject) => { const child = spawn(commandName, args, { cwd, shell: false, stdio: ['pipe', 'pipe', 'pipe'] }); let stdout = ''; let stderr = ''; child.stdout.on('data', (chunk) => { stdout += chunk; }); child.stderr.on('data', (chunk) => { stderr += chunk; }); child.on('error', reject); child.on('close', (code) => code === 0 ? resolve(stdout) : reject(new Error(`${commandName} failed (${code}): ${sanitize(stderr)}`))); child.stdin.end(input); }); }
const gh = (args) => execute('gh', args); const git = (args) => execute('git', args);
async function codexInvocation() { if (process.platform !== 'win32') return { command: codexCommand(), args: [] }; const shim = (await execute('where.exe', ['codex.cmd'])).split(/\r?\n/).find(Boolean); const entry = path.join(path.dirname(shim), 'node_modules', '@openai', 'codex', 'bin', 'codex.js'); await access(entry); return { command: process.execPath, args: [entry] }; }
const pathAllowed = (file) => ['package.json', 'package-lock.json', '.gitignore', '.env.example', 'README.md', 'AGENTS.md'].includes(file) || ['scripts/agent-bridge/', 'tests/agent-bridge/', 'docs/AGENT_BRIDGE.md', 'docs/BRIDGE_RUNBOOK.md', 'docs/BRIDGE_PILOT_LOG.md', 'docs/STACK.md'].some((prefix) => file.startsWith(prefix));
const adapter = {
  listReadyIssues: async () => JSON.parse(await gh(['issue', 'list', '--state', 'open', '--label', 'agent:ready', '--limit', '100', '--json', 'number,title,body,labels,createdAt'])),
  getIssue: async (number) => JSON.parse(await gh(['issue', 'view', String(number), '--json', 'number,title,body,labels,createdAt'])),
  claimIssue: async (number) => gh(['issue', 'edit', String(number), '--remove-label', 'agent:ready', '--add-label', 'agent:running', '--add-assignee', '@me']),
  blockIssue: async (number, message) => { await gh(['issue', 'edit', String(number), '--remove-label', 'agent:running', '--add-label', 'agent:blocked']); await gh(['issue', 'comment', String(number), '--body', message]); },
  handoff: async (number, id, branch, pullRequest) => { await gh(['issue', 'edit', String(number), '--remove-label', 'agent:running', '--add-label', 'agent:review']); await gh(['issue', 'comment', String(number), '--body', `Bridge handoff: run ${id}; branch ${branch}; PR #${pullRequest}; audit report stored locally.`]); },
  createWorktree: async (branch, worktree) => git(['worktree', 'add', '-b', branch, worktree, 'origin/main']),
  worktreePath: (workspace, branch) => path.join(workspace, '.agent-bridge', 'worktrees', branch.replaceAll('/', '-')),
  runCodex: async (prompt, cwd) => { const invocation = await codexInvocation(); return execute(invocation.command, [...invocation.args, 'exec', '--ephemeral', prompt], { cwd }); },
  acquireLock: (workspace) => acquireLock(workspace),
  writeAudit: (workspace, id, report) => writeAudit(workspace, id, report),
  getHandoffStatus: async (branch) => { const prs = JSON.parse(await gh(['pr', 'list', '--head', branch, '--state', 'open', '--json', 'number'])); if (prs.length !== 1) return { ready: false, reason: `handoff requires exactly one open pull request for ${branch}; found ${prs.length}` }; return { ready: true, number: prs[0].number }; },
  getMergeStatus: async (branch) => { const prs = JSON.parse(await gh(['pr', 'list', '--head', branch, '--state', 'open', '--json', 'number,isDraft,mergeStateStatus,statusCheckRollup,files'])); if (prs.length !== 1) return { policyEligible: false, requiredChecksPass: false, mergeable: false, clean: false }; const pr = prs[0]; const checks = pr.statusCheckRollup ?? []; return { number: pr.number, policyEligible: pr.files.every((file) => pathAllowed(file.path)), requiredChecksPass: checks.length > 0 && checks.every((check) => check.conclusion === 'SUCCESS'), mergeable: !pr.isDraft, clean: pr.mergeStateStatus === 'CLEAN' }; },
  mergePR: (number) => gh(['pr', 'merge', String(number), '--merge', '--delete-branch'])
};
async function doctor() { const checks = []; const codex = await codexInvocation().catch((error) => ({ error })); for (const [name, executable, args] of [['git', 'git', ['--version']], ['gh-auth', 'gh', ['auth', 'status']], ['codex', codex.command, [...(codex.args ?? []), 'exec', '--help']]]) { try { if (codex.error && name === 'codex') throw codex.error; await execute(executable, args); checks.push({ name, pass: true }); } catch (error) { checks.push({ name, pass: false, detail: sanitize(error.message) }); } } for (const file of requiredFiles) { try { await access(path.join(root, file)); checks.push({ name: file, pass: true }); } catch { checks.push({ name: file, pass: false }); } } const status = await git(['status', '--short']); const branch = (await git(['branch', '--show-current'])).trim(); checks.push({ name: 'clean-main', pass: branch === 'main' && status.trim() === '' }); try { const labels = JSON.parse(await gh(['label', 'list', '--limit', '100', '--json', 'name'])).map((label) => label.name); checks.push({ name: 'bridge-labels', pass: ['agent:ready', 'agent:running', 'agent:review', 'agent:blocked'].every((label) => labels.includes(label)) }); } catch (error) { checks.push({ name: 'bridge-labels', pass: false, detail: sanitize(error.message) }); } console.log(JSON.stringify({ command: 'doctor', defaults, checks }, null, 2)); if (checks.some((check) => !check.pass)) process.exitCode = 1; }
if (command === 'doctor') await doctor(); else if (command === 'once') console.log(JSON.stringify(await runOnce({ adapter, root, config }), null, 2)); else if (command === 'watch') console.log(JSON.stringify(await runWatch({ adapter, root, config }), null, 2)); else { console.error('Usage: bridge <doctor|once|watch> [--dry-run] [--auto-merge]'); process.exitCode = 2; }
