import test from 'node:test';
import assert from 'node:assert/strict';
import { autoMergeAllowed, branchFor, changedPaths, codexCommand, defaults, eligible, issueAllowedPaths, parseConfig, promptFor, runOnce, runWatch, sanitize, selectOldestEligible, validateChangedPaths } from '../../scripts/agent-bridge/core.mjs';

const body = `### Goal\nGlossary\n\n### In scope\n- Define the terms Architect, Implementer, Owner, issue contract, PR contract, agent:validate, agent:ready, agent:running, agent:review, agent:blocked, run ID, claim, lease, durable handoff, worktree, repair cycle, dry-run, auto-merge, audit report, doctor, bridge:once, bridge:watch, and kill switch.\n\n### Allowed paths\n- \`docs/BRIDGE_GLOSSARY.md\`\n- \`README.md\`\n- \`docs/BRIDGE_RUNBOOK.md\``;
const ready = { number: 12, title: 'Document safety', body, createdAt: '2026-01-01T00:00:00Z', labels: [{ name: 'agent:ready' }], assignees: [{ login: 'NastyBaster' }] };

function mockAdapter(overrides = {}) {
  const calls = []; const audits = []; const progress = [];
  return { calls, audits, progress, listReadyIssues: async () => [ready], getIssue: async () => ready, claimIssue: async () => calls.push('claim'), createWorktree: async () => calls.push('worktree'), worktreePath: () => 'isolated-worktree', runCodex: async (_, __, options) => { options?.onProgress?.({ phase: 'run-child', event: 'heartbeat' }); return { exitCode: 0, outcome: 'complete', summary: 'changed files' }; }, inspectWorktree: async () => ({ changedPaths: ['docs/BRIDGE_GLOSSARY.md'] }), validateChanges: async () => calls.push('validate'), runChecks: async () => [{ name: 'git diff --check', pass: true }], commit: async () => { calls.push('commit'); return 'abc123'; }, push: async () => calls.push('push'), createPR: async () => { calls.push('create-pr'); return { number: 99 }; }, getHandoffStatus: async () => ({ ready: true, number: 99 }), handoff: async () => calls.push('handoff'), waitForChecks: async () => ({ pass: true, checks: [{ name: 'validate', pass: true }] }), getMergeStatus: async () => ({ number: 99, policyEligible: true, requiredChecksPass: true, mergeable: true, clean: true }), mergePR: async () => calls.push('merge'), verifyClosure: async () => true, cleanup: async () => { calls.push('cleanup'); return { removed: true }; }, blockIssue: async (_, message) => calls.push(`block:${message}`), acquireLock: async () => { calls.push('lock'); return async () => calls.push('unlock'); }, writeAudit: async (_, __, report) => audits.push(structuredClone(report)), ...overrides };
}

test('defaults are bounded and safe', () => assert.deepEqual(defaults, { concurrency: 1, maxTasks: 3, maxRepairCycles: 2, maxTaskMinutes: 90, pollSeconds: 30, dryRun: true, autoMerge: false }));
test('discovery selects oldest and excludes active issues', async () => { const older = { ...ready, number: 11, createdAt: '2025-01-01T00:00:00Z' }; assert.equal((await selectOldestEligible({ listReadyIssues: async () => [{ ...ready, labels: [{ name: 'agent:ready' }, { name: 'agent:running' }] }, ready, older] })).number, 11); assert.equal(eligible({ labels: [{ name: 'agent:ready' }, { name: 'agent:review' }] }), false); });
test('dry run never claims or creates worktree', async () => { const adapter = mockAdapter(); assert.equal((await runOnce({ adapter, root: '.', config: defaults, id: 'test' })).outcome, 'dry-run'); assert.deepEqual(adapter.calls, []); });
test('preclaimed child receives scoped context and parent owns lifecycle', () => { const prompt = promptFor(ready, 'run-1', { branch: 'agent/12-document-safety', worktree: 'isolated-worktree', assignee: 'NastyBaster' }); assert.match(prompt, /"parentClaimed": true/); assert.match(prompt, /agent\/12-document-safety/); assert.match(prompt, /do not require agent:ready/); assert.match(prompt, /parentOwns/); assert.match(prompt, /Do not create commits/); });
test('successful parent lifecycle commits, pushes, reviews, merges, and cleans', async () => { const adapter = mockAdapter(); const events = []; const result = await runOnce({ adapter, root: '.', config: { ...defaults, dryRun: false, autoMerge: true }, id: 'test', progress: (event) => events.push(event) }); assert.equal(result.outcome, 'complete'); assert.deepEqual(adapter.calls, ['lock', 'claim', 'worktree', 'validate', 'commit', 'push', 'create-pr', 'handoff', 'merge', 'cleanup', 'unlock']); assert.equal(adapter.audits.at(-1).child.exitCode, 0); assert.equal(adapter.audits.at(-1).commit, 'abc123'); assert.equal(adapter.audits.at(-1).pullRequest, 99); assert.ok(events.some((event) => event.phase === 'run-child' && event.event === 'heartbeat')); });
test('no-change child becomes blocked and never commits or hands off', async () => { const adapter = mockAdapter({ inspectWorktree: async () => ({ changedPaths: [] }) }); const result = await runOnce({ adapter, root: '.', config: { ...defaults, dryRun: false }, id: 'test' }); assert.equal(result.outcome, 'blocked'); assert.match(result.error, /no changes/); assert.equal(adapter.calls.includes('commit'), false); assert.ok(adapter.calls.some((call) => call.startsWith('block:'))); });
test('invalid paths are refused before commit', async () => { const adapter = mockAdapter({ inspectWorktree: async () => ({ changedPaths: ['src/secret.txt'] }) }); const result = await runOnce({ adapter, root: '.', config: { ...defaults, dryRun: false }, id: 'test' }); assert.equal(result.outcome, 'blocked'); assert.match(result.error, /out-of-scope/); assert.equal(adapter.calls.includes('commit'), false); });
test('child failure, commit failure, push failure, PR failure, check failure, and closure failure block', async () => { for (const overrides of [{ runCodex: async () => ({ exitCode: 1 }) }, { commit: async () => { throw new Error('commit failed'); } }, { push: async () => { throw new Error('push failed'); } }, { createPR: async () => { throw new Error('PR failed'); } }, { waitForChecks: async () => ({ pass: false, checks: [] }) }, { verifyClosure: async () => false }]) { const adapter = mockAdapter(overrides); const result = await runOnce({ adapter, root: '.', config: { ...defaults, dryRun: false, autoMerge: true }, id: 'test' }); assert.equal(result.outcome, 'blocked'); assert.ok(adapter.calls.some((call) => call.startsWith('block:'))); } });
test('changed path and status parsing reject traversal', () => { assert.deepEqual(changedPaths(' M README.md\n?? docs/new.md'), ['README.md', 'docs/new.md']); assert.equal(validateChangedPaths(['README.md'], ['README.md']).valid, true); assert.equal(validateChangedPaths(['../bad'], ['README.md']).valid, false); assert.deepEqual(issueAllowedPaths(ready), ['docs/BRIDGE_GLOSSARY.md', 'README.md', 'docs/BRIDGE_RUNBOOK.md']); });
test('auto merge requires all explicit gates', () => { assert.equal(autoMergeAllowed({ policyEligible: true, requiredChecksPass: true, autoMerge: true, mergeable: true, clean: true }), true); assert.equal(autoMergeAllowed({ policyEligible: true, requiredChecksPass: true, autoMerge: true, mergeable: false, clean: true }), false); });
test('watch stays bounded without nested loop', async () => { let sleeps = 0; const results = await runWatch({ adapter: {}, root: '.', config: { ...defaults, maxTasks: 2 }, run: async () => ({ outcome: 'dry-run' }), sleep: async () => { sleeps += 1; } }); assert.equal(results.length, 2); assert.equal(sleeps, 1); });
test('configuration, platform command, and sanitizer are safe', () => { assert.equal(parseConfig([], {}).dryRun, true); assert.equal(parseConfig(['--dry-run'], { BRIDGE_DRY_RUN: 'false' }).dryRun, true); assert.equal(parseConfig([], { BRIDGE_POLL_SECONDS: '3' }).pollSeconds, 30); assert.equal(codexCommand('win32'), 'codex.cmd'); assert.match(sanitize('ghp_test C:\\private\\file'), /\[redacted\].*\[private-path\]/); assert.match(branchFor(ready), /^agent\/12-/); });
