import test from 'node:test';
import assert from 'node:assert/strict';
import { autoMergeAllowed, branchFor, codexCommand, defaults, eligible, parseConfig, promptFor, runOnce, runWatch, sanitize, selectOldestEligible } from '../../scripts/agent-bridge/core.mjs';
const ready = { number: 12, title: 'Document safety', body: '$(not-a-command)', createdAt: '2026-01-01T00:00:00Z', labels: [{ name: 'agent:ready' }] };
function mockAdapter(overrides = {}) { const calls = []; return { calls, listReadyIssues: async () => [ready], getIssue: async () => ready, claimIssue: async () => calls.push('claim'), createWorktree: async () => calls.push('worktree'), worktreePath: () => 'isolated-worktree', runCodex: async () => 'completed', handoff: async () => calls.push('handoff'), blockIssue: async (_, message) => calls.push(`block:${message}`), acquireLock: async () => { calls.push('lock'); return async () => calls.push('unlock'); }, writeAudit: async () => calls.push('audit'), ...overrides }; }
test('defaults are bounded and safe', () => { assert.deepEqual(defaults, { concurrency: 1, maxTasks: 3, maxRepairCycles: 2, maxTaskMinutes: 90, pollSeconds: 30, dryRun: true, autoMerge: false }); });
test('discovery selects oldest and excludes active issues', async () => { const older = { ...ready, number: 11, createdAt: '2025-01-01T00:00:00Z' }; assert.equal((await selectOldestEligible({ listReadyIssues: async () => [{ ...ready, labels: [{ name: 'agent:ready' }, { name: 'agent:running' }] }, ready, older] })).number, 11); assert.equal(eligible({ labels: [{ name: 'agent:ready' }, { name: 'agent:review' }] }), false); });
test('dry run never claims or creates worktree', async () => { const adapter = mockAdapter(); assert.equal((await runOnce({ adapter, root: '.', config: defaults, id: 'test' })).outcome, 'dry-run'); assert.deepEqual(adapter.calls, []); });
test('claim refusal is idempotent after concurrent state change', async () => { const adapter = mockAdapter({ getIssue: async () => ({ ...ready, labels: [{ name: 'agent:running' }] }) }); assert.equal((await runOnce({ adapter, root: '.', config: { ...defaults, dryRun: false }, id: 'test' })).outcome, 'claim-refused'); assert.deepEqual(adapter.calls, ['lock', 'unlock']); });
test('successful handoff uses worktree and untrusted prompt', async () => { let prompt = ''; const adapter = mockAdapter({ runCodex: async (value) => { prompt = value; return 'done'; } }); assert.equal((await runOnce({ adapter, root: '.', config: { ...defaults, dryRun: false }, id: 'test' })).outcome, 'handoff'); assert.deepEqual(adapter.calls, ['lock', 'claim', 'worktree', 'audit', 'handoff', 'unlock']); assert.match(prompt, /untrusted data/); assert.match(prompt, /\$\(not-a-command\)/); assert.match(branchFor(ready), /^agent\/12-/); });
test('auto merge requires all explicit gates', async () => { const adapter = mockAdapter({ getMergeStatus: async () => ({ number: 99, policyEligible: true, requiredChecksPass: true, mergeable: true, clean: true }), mergePR: async () => adapter.calls.push('merge') }); const result = await runOnce({ adapter, root: '.', config: { ...defaults, dryRun: false, autoMerge: true }, id: 'test' }); assert.equal(result.autoMerged, true); assert.ok(adapter.calls.includes('merge')); });
test('failure blocks with sanitized summary', async () => { const adapter = mockAdapter({ runCodex: async () => { throw new Error('ghp_test C:\\private\\file'); } }); assert.equal((await runOnce({ adapter, root: '.', config: { ...defaults, dryRun: false }, id: 'test' })).outcome, 'blocked'); assert.match(adapter.calls.find((call) => call.startsWith('block:')), /\[redacted\].*\[private-path\]/); });
test('watch stays bounded without nested loop in tests', async () => { let sleeps = 0; const results = await runWatch({ adapter: {}, root: '.', config: { ...defaults, maxTasks: 2 }, run: async () => ({ outcome: 'dry-run' }), sleep: async () => { sleeps += 1; } }); assert.equal(results.length, 2); assert.equal(sleeps, 1); });
test('configuration, platform command, merge gates and sanitizer are safe', () => { assert.equal(parseConfig([], {}).dryRun, true); assert.equal(parseConfig(['--dry-run'], { BRIDGE_DRY_RUN: 'false' }).dryRun, true); assert.equal(parseConfig([], { BRIDGE_POLL_SECONDS: '3' }).pollSeconds, 30); assert.equal(codexCommand('win32'), 'codex.cmd'); assert.equal(autoMergeAllowed({ policyEligible: true, requiredChecksPass: true, autoMerge: true, mergeable: true, clean: true }), true); assert.equal(autoMergeAllowed({ policyEligible: true, requiredChecksPass: true, autoMerge: true, mergeable: false, clean: true }), false); assert.equal(sanitize('ghp_test C:\\private\\file'), '[redacted] [private-path]'); assert.match(promptFor(ready, 'id'), /UNTRUSTED ISSUE BODY/); });
