import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { acquireOwnership, archiveAndRemoveChild, listChildren, readOwner, registerChild, updateChild } from '../../scripts/agent-bridge/ownership.mjs';

async function workspace() { return mkdtemp(path.join(os.tmpdir(), 'bridge-ownership-')); }
const options = (mode = 'batch', runId = 'run-1') => ({ mode, runId, ownerPid: 100, ownerStartIdentity: 'start-100', tokenGenerator: () => 'a'.repeat(64), now: () => 1_700_000_000_000 });

test('atomic owner acquisition and exact token release', async () => { const root = await workspace(); try { const owner = await acquireOwnership(root, options()); const record = await readOwner(root); assert.equal(record.mode, 'batch'); assert.equal(record.runId, 'run-1'); assert.equal(record.ownerPid, 100); await assert.rejects(acquireOwnership(root, { ...options(), tokenGenerator: () => 'b'.repeat(64) }), /live|malformed|controlled stale/); await owner.release(); await assert.rejects(readOwner(root)); } finally { await rm(root, { recursive: true, force: true }); } });
test('once, batch and watch use the same lock', async () => { const root = await workspace(); try { for (const mode of ['once', 'batch', 'watch']) { const owner = await acquireOwnership(root, options(mode, mode)); await assert.rejects(acquireOwnership(root, options('once', 'second')), /live|controlled stale/); await owner.release(); } } finally { await rm(root, { recursive: true, force: true }); } });
test('malformed and repository-mismatched owners fail closed', async () => { const root = await workspace(); try { await mkdir(path.join(root, '.agent-bridge')); await writeFile(path.join(root, '.agent-bridge', 'execution-owner.json'), '{bad'); await assert.rejects(acquireOwnership(root, options()), /malformed/); } finally { await rm(root, { recursive: true, force: true }); } });
test('heartbeat requires the owner capability and updates lease', async () => { const root = await workspace(); try { const owner = await acquireOwnership(root, options()); await owner.heartbeat(1_700_000_010_000); assert.equal((await readOwner(root)).heartbeatAt, new Date(1_700_000_010_000).toISOString()); await owner.release(); } finally { await rm(root, { recursive: true, force: true }); } });
test('child registry records ownership and removes active entry after terminal archive', async () => { const root = await workspace(); try { const owner = await acquireOwnership(root, options()); const child = await registerChild(root, owner, { batchId: 'batch-1', runId: 'child-1', sequence: 1, issueNumber: 49, childPid: 200, childStartIdentity: 'start-200' }); assert.equal(child.ownerTokenFingerprint.length, 16); assert.equal((await listChildren(root)).length, 1); await archiveAndRemoveChild(root, owner, 'child-1', { state: 'complete', exitCode: 0 }); assert.equal((await listChildren(root)).length, 0); await owner.release(); } finally { await rm(root, { recursive: true, force: true }); } });
test('missing or wrong delegated capability cannot register a child', async () => { const root = await workspace(); try { const owner = await acquireOwnership(root, options()); await assert.rejects(registerChild(root, { ownershipToken: 'b'.repeat(64) }, { batchId: 'b', runId: 'c', sequence: 1, childPid: 2, childStartIdentity: 's' }), /mismatch/); await owner.release(); } finally { await rm(root, { recursive: true, force: true }); } });
test('unrelated ambient process is ignored without registry', async () => { const { classifyBridgeProcesses } = await import('../../scripts/agent-bridge/process-health.mjs'); const result = classifyBridgeProcesses([{ pid: 1, ppid: 0, name: 'codex.exe', command: 'codex exec "npm run bridge:watch"', startTime: 's' }]); assert.equal(result.pass, true); assert.equal(result.processes[0].category, 'unrelated_process'); });
test('registered PID identity mismatch is stale and non-blocking', async () => { const { classifyRegisteredProcesses } = await import('../../scripts/agent-bridge/process-health.mjs'); const result = classifyRegisteredProcesses([{ pid: 200, ppid: 1, name: 'node.exe', command: 'node unrelated', startTime: 'new' }], { owner: null, children: [{ childPid: 200, childStartIdentity: 'old', batchId: 'b', runId: 'c' }] }); assert.equal(result.pass, true); assert.equal(result.processes[0].category, 'stale_pid_record'); });
