import test from 'node:test';
import assert from 'node:assert/strict';
import { classifyBridgeCommand, classifyBridgeProcesses, inspectWindowsProcessSnapshot, normalizeProcessSnapshot, parseWindowsProcessSnapshot, parseWindowsCommandLine, windowsProcessSnapshotArgs } from '../../scripts/agent-bridge/process-health.mjs';

const p = (pid, command, extras = {}) => ({ pid, ppid: extras.ppid ?? 1, name: extras.name ?? 'node.exe', command, startTime: extras.startTime ?? `s-${pid}` });
const context = { platform: 'win32', currentProcess: { pid: 10, startTime: 's-10' } };
const category = (command, extras = {}) => classifyBridgeProcesses([p(10, 'node scripts/agent-bridge/cli.mjs batch'), p(20, command, extras)], context);

test('reviewer fixture is an exact blocking watcher', () => { const result = category('node scripts/agent-bridge/cli.mjs watch'); assert.equal(result.pass, false); assert.equal(result.processes[1].category, 'bridge_watch'); assert.equal(result.blocking[0].reason, 'exact Bridge watch entrypoint detected'); });
test('direct Node watcher forms are exact and path normalized', () => { for (const command of ['node scripts/agent-bridge/cli.mjs watch', 'node.exe scripts\\agent-bridge\\cli.mjs watch', '"C:\\Program Files\\nodejs\\node.exe" "C:\\Work Space\\scripts\\agent-bridge\\cli.mjs" watch', 'node --inspect=9229 scripts/agent-bridge/cli.mjs watch']) assert.equal(category(command).blocking[0].category, 'bridge_watch'); });
test('npm and npm Node launchers are exact watchers', () => { for (const [name, command] of [['npm', 'npm run bridge:watch'], ['npm.cmd', 'npm.cmd run bridge:watch'], ['npm.exe', 'npm.exe run bridge:watch'], ['node.exe', 'node "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" run bridge:watch']]) assert.equal(category(command, { name }).blocking[0].category, 'bridge_watch'); });
test('cmd and PowerShell wrappers require a leading npm invocation', () => { for (const [name, command] of [['cmd.exe', 'cmd.exe /c npm run bridge:watch'], ['cmd.exe', 'cmd.exe /d /s /c npm.cmd run bridge:watch'], ['powershell.exe', 'powershell.exe -NoProfile -Command "npm run bridge:watch"'], ['pwsh.exe', 'pwsh.exe -Command npm.cmd run bridge:watch']]) assert.equal(category(command, { name }).blocking[0].category, 'bridge_watch'); });
test('current batch and verified launcher are allowed but descendant watcher blocks', () => { const result = classifyBridgeProcesses([p(10, 'node scripts/agent-bridge/cli.mjs batch', { ppid: 9 }), p(9, 'npm run bridge:batch', { name: 'npm.cmd' }), p(20, 'node scripts/agent-bridge/cli.mjs watch', { ppid: 9 })], context); assert.equal(result.processes[0].category, 'current_batch'); assert.equal(result.processes[1].category, 'verified_launcher'); assert.equal(result.processes[2].category, 'bridge_watch'); assert.equal(result.pass, false); });
test('current batch/once/doctor PID is allowed by current-run priority', () => { for (const command of ['node scripts/agent-bridge/cli.mjs batch', 'node scripts/agent-bridge/cli.mjs once', 'node scripts/agent-bridge/cli.mjs doctor']) { const result = classifyBridgeProcesses([p(20, command)], { platform: 'win32', currentProcess: { pid: 20, startTime: 's-20' } }); assert.equal(result.pass, true); assert.equal(result.processes[0].category, 'current_batch'); } });
test('untracked Bridge batch/once launcher is ambiguous and blocking', () => { for (const command of ['node scripts/agent-bridge/cli.mjs batch', 'node scripts/agent-bridge/cli.mjs once', 'node scripts/agent-bridge/cli.mjs doctor', 'npm run bridge:batch', 'npm run bridge:once']) { const name = command.startsWith('npm') ? 'npm.cmd' : 'node.exe'; assert.equal(category(command, { name }).blocking[0].category, 'ambiguous_bridge_process'); } });
test('tracked live child blocks and PID reuse is stale', () => { const live = classifyBridgeProcesses([p(10, 'node scripts/agent-bridge/cli.mjs batch'), p(30, 'codex exec task')], { ...context, trackedChildren: [{ pid: 30, startTime: 's-30', commandIdentity: 'codex exec' }] }); assert.equal(live.blocking[0].category, 'tracked_task_child'); const reused = classifyBridgeProcesses([p(10, 'node scripts/agent-bridge/cli.mjs batch'), p(30, 'node unrelated')], { ...context, trackedChildren: [{ pid: 30, startTime: 'old-start', commandIdentity: 'codex exec' }] }); assert.equal(reused.pass, true); assert.equal(reused.processes[1].category, 'stale_pid_record'); });
test('live watcher record needs matching start identity', () => { const live = classifyBridgeProcesses([p(10, 'node scripts/agent-bridge/cli.mjs batch'), p(20, 'node unrelated')], { ...context, watcherRecords: [{ pid: 20, startTime: 's-20' }] }); assert.equal(live.blocking[0].category, 'bridge_watch'); const stale = classifyBridgeProcesses([p(10, 'node scripts/agent-bridge/cli.mjs batch'), p(20, 'node unrelated')], { ...context, watcherRecords: [{ pid: 20, startTime: 'old' }] }); assert.equal(stale.pass, true); assert.equal(stale.processes[1].category, 'stale_pid_record'); });
test('Codex, prompts, search, editor, test runner and unrelated Node stay non-blocking', () => { const commands = [['codex.exe', 'codex exec --ephemeral "node scripts/agent-bridge/cli.mjs watch"'], ['codex.exe', 'codex exec --ephemeral "npm run bridge:watch"'], ['rg.exe', 'rg "cli.mjs watch" .'], ['Code.exe', 'Code.exe --search "bridge:watch"'], ['node.exe', 'node test-runner.js "node scripts/agent-bridge/cli.mjs watch"'], ['node.exe', 'node unrelated.js watch']]; for (const [name, command] of commands) { const result = category(command, { name }); assert.equal(result.pass, true, command); assert.equal(result.processes[1].category, 'unrelated_process', command); } });
test('similar paths and npm script names are not exact watcher commands', () => { for (const command of ['node scripts/not-agent-bridge/cli.mjs watch', 'npm run bridge:watch-example', 'npm run bridge:watch-more']) { const result = category(command, { name: command.startsWith('npm') ? 'npm.cmd' : 'node.exe' }); assert.equal(result.pass, true); assert.equal(result.processes[1].category, 'unrelated_process'); } });
test('ambiguous Bridge-looking commands fail closed', () => { for (const [name, command] of [['cmd.exe', 'cmd.exe /c echo npm run bridge:watch'], ['powershell.exe', 'powershell.exe -Command "Write-Output bridge:watch"'], ['node.exe', 'node scripts/agent-bridge/cli.mjs unknown'], ['node.exe', 'node "unterminated scripts/agent-bridge/cli.mjs watch']]) { const result = category(command, { name }); assert.equal(result.pass, false); assert.equal(result.processes[1].category, 'ambiguous_bridge_process'); } });
test('parser handles quotes, empty args and malformed input', () => { assert.deepEqual(parseWindowsCommandLine('"C:\\Program Files\\node.exe" "C:\\Work Space\\cli.mjs" watch'), { args: ['C:\\Program Files\\node.exe', 'C:\\Work Space\\cli.mjs', 'watch'], malformed: false }); assert.deepEqual(parseWindowsCommandLine('node "" watch'), { args: ['node', '', 'watch'], malformed: false }); assert.equal(parseWindowsCommandLine('node "unterminated').malformed, true); });
test('normalized Windows CIM records expose structured identity', () => { const result = normalizeProcessSnapshot({ ProcessId: 10, ParentProcessId: 1, Name: 'node.exe', CommandLine: 'node scripts\\agent-bridge\\cli.mjs watch', CreationDate: 'start' }, { platform: 'win32' }); assert.deepEqual(result[0].parsedArgs, ['node', 'scripts\\agent-bridge\\cli.mjs', 'watch']); assert.equal(result[0].executable, 'node.exe'); assert.equal(result[0].platform, 'win32'); });
test('classifyBridgeCommand is pure and structural', () => { assert.equal(classifyBridgeCommand({ name: 'node.exe', command: 'node scripts/agent-bridge/cli.mjs watch' }).kind, 'watch'); assert.equal(classifyBridgeCommand({ name: 'codex.exe', command: 'codex "npm run bridge:watch"' }).kind, null); });
test('sanitized results omit raw command, executable and prompt arguments', () => { const result = category('codex.exe exec --ephemeral "node scripts/agent-bridge/cli.mjs watch"', { name: 'codex.exe' }); const serialized = JSON.stringify(result); assert.equal(serialized.includes('ephemeral'), false); assert.equal(serialized.includes('scripts/agent-bridge'), false); for (const record of result.processes) assert.deepEqual(Object.keys(record).sort(), ['category', 'identityMatch', 'parentPid', 'pid', 'reason', 'relation']); });
test('malformed snapshots fail closed and import has no process side effects', () => { assert.throws(() => normalizeProcessSnapshot(null)); assert.equal(normalizeProcessSnapshot([{ pid: 1, name: 'node.exe' }])[0].command, null); assert.equal(classifyBridgeProcesses([], context).pass, true); });

const cimRecord = (overrides = {}) => ({ ProcessId: 10, ParentProcessId: 0, Name: 'node.exe', ExecutablePath: null, CommandLine: null, CreationDate: null, ...overrides });
test('Windows parser accepts deterministic empty, singleton and multi-record arrays', () => { assert.deepEqual(parseWindowsProcessSnapshot('[]'), []); assert.equal(parseWindowsProcessSnapshot(JSON.stringify([cimRecord()])).length, 1); assert.equal(parseWindowsProcessSnapshot(JSON.stringify([cimRecord(), cimRecord({ ProcessId: 11 })])).length, 2); });
test('Windows parser strips BOM, CRLF and surrounding whitespace', () => { const raw = `\uFEFF  [\r\n ${JSON.stringify(cimRecord({ CommandLine: 'node test.js' }))}\r\n ]  `; assert.equal(parseWindowsProcessSnapshot(Buffer.from(raw))[0].command, 'node test.js'); });
test('Windows parser rejects empty, null, object, malformed and trailing output', () => { for (const raw of ['', 'null', '{}', '{bad}', '[]warning']) assert.throws(() => parseWindowsProcessSnapshot(raw)); });
test('Windows parser permits legal null optional CIM fields and zero parent PID', () => { const [record] = parseWindowsProcessSnapshot(JSON.stringify([cimRecord()])); assert.equal(record.ppid, 0); assert.equal(record.command, null); assert.equal(record.executablePath, null); assert.equal(record.startTime, null); });
test('Windows parser validates identity fields and duplicate/mixed records fail closed', () => { for (const record of [cimRecord({ ProcessId: undefined }), cimRecord({ ProcessId: -1 }), cimRecord({ ProcessId: 1.5 }), cimRecord({ ParentProcessId: -1 }), cimRecord({ ProcessId: 10 }),]) { const input = record.ProcessId === 10 && record !== undefined ? [record, cimRecord({ ProcessId: 10 })] : [record]; assert.throws(() => parseWindowsProcessSnapshot(JSON.stringify(input))); } assert.throws(() => parseWindowsProcessSnapshot(JSON.stringify([cimRecord(), { Name: 'node.exe' }]))); });
test('actual failed inspection shape is parsed without trusting missing identity evidence', () => { const [record] = parseWindowsProcessSnapshot(JSON.stringify([cimRecord({ ProcessId: 20, Name: 'node.exe' })])); const result = classifyBridgeProcesses([record], { platform: 'win32', currentProcess: { pid: 10, startTime: 'missing' } }); assert.equal(result.pass, false); assert.equal(result.blocking[0].category, 'ambiguous_bridge_process'); });
test('PowerShell adapter has an explicit array, deterministic and JSON-only command contract', async () => { assert.deepEqual(windowsProcessSnapshotArgs.slice(0, 2), ['-NoProfile', '-NonInteractive']); assert.equal(windowsProcessSnapshotArgs[2], '-Command'); assert.match(windowsProcessSnapshotArgs[3], /\$records = @\(/); assert.match(windowsProcessSnapshotArgs[3], /ConvertTo-Json -InputObject \$records/); const calls = []; const inspected = await inspectWindowsProcessSnapshot({ run: async (...args) => { calls.push(args); return { exitCode: 0, stdout: Buffer.from(`\uFEFF[${JSON.stringify(cimRecord())}]\r\n`), stderr: '' }; } }); assert.equal(inspected.ok, true); assert.equal(calls[0][0], 'powershell.exe'); assert.deepEqual(calls[0][1], windowsProcessSnapshotArgs); });
test('PowerShell adapter fails closed for command failure and unexpected stderr', async () => { const failed = await inspectWindowsProcessSnapshot({ run: async () => ({ exitCode: 1, stdout: '', stderr: 'permission denied' }) }); assert.equal(failed.ok, false); assert.equal(failed.error.category, 'process_inspection_command_failed'); const noisy = await inspectWindowsProcessSnapshot({ run: async () => ({ exitCode: 0, stdout: '[]', stderr: 'warning' }) }); assert.equal(noisy.ok, false); assert.equal(noisy.error.category, 'windows_snapshot_unexpected_stderr'); });
test('missing optional command evidence remains conservative while current batch is allowed', () => { const result = classifyBridgeProcesses([cimRecord({ ProcessId: 10, CommandLine: null })], { platform: 'win32', currentProcess: { pid: 10 } }); assert.equal(result.pass, true); assert.equal(result.processes[0].category, 'current_batch'); });
